// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/seal-io/walrus/pkg/apis/walrusutil/v1"
	walrusutilv1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walrusutil/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScheduleTasks implements ScheduleTaskInterface
type FakeScheduleTasks struct {
	Fake *FakeWalrusutilV1
	ns   string
}

var scheduletasksResource = v1.SchemeGroupVersion.WithResource("scheduletasks")

var scheduletasksKind = v1.SchemeGroupVersion.WithKind("ScheduleTask")

// Get takes name of the scheduleTask, and returns the corresponding scheduleTask object, and an error if there is any.
func (c *FakeScheduleTasks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ScheduleTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scheduletasksResource, c.ns, name), &v1.ScheduleTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ScheduleTask), err
}

// List takes label and field selectors, and returns the list of ScheduleTasks that match those selectors.
func (c *FakeScheduleTasks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ScheduleTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scheduletasksResource, scheduletasksKind, c.ns, opts), &v1.ScheduleTaskList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ScheduleTaskList{ListMeta: obj.(*v1.ScheduleTaskList).ListMeta}
	for _, item := range obj.(*v1.ScheduleTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scheduleTasks.
func (c *FakeScheduleTasks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scheduletasksResource, c.ns, opts))

}

// Create takes the representation of a scheduleTask and creates it.  Returns the server's representation of the scheduleTask, and an error, if there is any.
func (c *FakeScheduleTasks) Create(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.CreateOptions) (result *v1.ScheduleTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scheduletasksResource, c.ns, scheduleTask), &v1.ScheduleTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ScheduleTask), err
}

// Update takes the representation of a scheduleTask and updates it. Returns the server's representation of the scheduleTask, and an error, if there is any.
func (c *FakeScheduleTasks) Update(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.UpdateOptions) (result *v1.ScheduleTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scheduletasksResource, c.ns, scheduleTask), &v1.ScheduleTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ScheduleTask), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeScheduleTasks) UpdateStatus(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.UpdateOptions) (*v1.ScheduleTask, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scheduletasksResource, "status", c.ns, scheduleTask), &v1.ScheduleTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ScheduleTask), err
}

// Delete takes name of the scheduleTask and deletes it. Returns an error if one occurs.
func (c *FakeScheduleTasks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(scheduletasksResource, c.ns, name, opts), &v1.ScheduleTask{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScheduleTasks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scheduletasksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ScheduleTaskList{})
	return err
}

// Patch applies the patch and returns the patched scheduleTask.
func (c *FakeScheduleTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ScheduleTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scheduletasksResource, c.ns, name, pt, data, subresources...), &v1.ScheduleTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ScheduleTask), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied scheduleTask.
func (c *FakeScheduleTasks) Apply(ctx context.Context, scheduleTask *walrusutilv1.ScheduleTaskApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ScheduleTask, err error) {
	if scheduleTask == nil {
		return nil, fmt.Errorf("scheduleTask provided to Apply must not be nil")
	}
	data, err := json.Marshal(scheduleTask)
	if err != nil {
		return nil, err
	}
	name := scheduleTask.Name
	if name == nil {
		return nil, fmt.Errorf("scheduleTask.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scheduletasksResource, c.ns, *name, types.ApplyPatchType, data), &v1.ScheduleTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ScheduleTask), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeScheduleTasks) ApplyStatus(ctx context.Context, scheduleTask *walrusutilv1.ScheduleTaskApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ScheduleTask, err error) {
	if scheduleTask == nil {
		return nil, fmt.Errorf("scheduleTask provided to Apply must not be nil")
	}
	data, err := json.Marshal(scheduleTask)
	if err != nil {
		return nil, err
	}
	name := scheduleTask.Name
	if name == nil {
		return nil, fmt.Errorf("scheduleTask.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scheduletasksResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.ScheduleTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ScheduleTask), err
}
