// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// BasicAuthObjectReferenceApplyConfiguration represents an declarative configuration of the BasicAuthObjectReference type for use
// with apply.
type BasicAuthObjectReferenceApplyConfiguration struct {
	LocalObjectReferenceApplyConfiguration `json:",inline"`
}

// BasicAuthObjectReferenceApplyConfiguration constructs an declarative configuration of the BasicAuthObjectReference type for use with
// apply.
func BasicAuthObjectReference() *BasicAuthObjectReferenceApplyConfiguration {
	return &BasicAuthObjectReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BasicAuthObjectReferenceApplyConfiguration) WithName(value string) *BasicAuthObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}
