// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// FilteringApplyConfiguration represents an declarative configuration of the Filtering type for use
// with apply.
type FilteringApplyConfiguration struct {
	IncludeFilter *string `json:"includeFilter,omitempty"`
	ExcludeFilter *string `json:"excludeFilter,omitempty"`
}

// FilteringApplyConfiguration constructs an declarative configuration of the Filtering type for use with
// apply.
func Filtering() *FilteringApplyConfiguration {
	return &FilteringApplyConfiguration{}
}

// WithIncludeFilter sets the IncludeFilter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludeFilter field is set to the value of the last call.
func (b *FilteringApplyConfiguration) WithIncludeFilter(value string) *FilteringApplyConfiguration {
	b.IncludeFilter = &value
	return b
}

// WithExcludeFilter sets the ExcludeFilter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExcludeFilter field is set to the value of the last call.
func (b *FilteringApplyConfiguration) WithExcludeFilter(value string) *FilteringApplyConfiguration {
	b.ExcludeFilter = &value
	return b
}
