// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// HelmOCIChartApplyConfiguration represents an declarative configuration of the HelmOCIChart type for use
// with apply.
type HelmOCIChartApplyConfiguration struct {
	BasicAuthApplyConfiguration `json:",inline"`
	URL                         *string `json:"url,omitempty"`
}

// HelmOCIChartApplyConfiguration constructs an declarative configuration of the HelmOCIChart type for use with
// apply.
func HelmOCIChart() *HelmOCIChartApplyConfiguration {
	return &HelmOCIChartApplyConfiguration{}
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *HelmOCIChartApplyConfiguration) WithUsername(value string) *HelmOCIChartApplyConfiguration {
	b.Username = &value
	return b
}

// WithPassword sets the Password field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Password field is set to the value of the last call.
func (b *HelmOCIChartApplyConfiguration) WithPassword(value string) *HelmOCIChartApplyConfiguration {
	b.Password = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *HelmOCIChartApplyConfiguration) WithSecretRef(value *LocalObjectReferenceApplyConfiguration) *HelmOCIChartApplyConfiguration {
	b.SecretRef = value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *HelmOCIChartApplyConfiguration) WithURL(value string) *HelmOCIChartApplyConfiguration {
	b.URL = &value
	return b
}
