// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// OriginalUISchemaObjectReferenceApplyConfiguration represents an declarative configuration of the OriginalUISchemaObjectReference type for use
// with apply.
type OriginalUISchemaObjectReferenceApplyConfiguration struct {
	LocalObjectReferenceApplyConfiguration `json:",inline"`
}

// OriginalUISchemaObjectReferenceApplyConfiguration constructs an declarative configuration of the OriginalUISchemaObjectReference type for use with
// apply.
func OriginalUISchemaObjectReference() *OriginalUISchemaObjectReferenceApplyConfiguration {
	return &OriginalUISchemaObjectReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OriginalUISchemaObjectReferenceApplyConfiguration) WithName(value string) *OriginalUISchemaObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}
