// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SchemaObjectReferenceApplyConfiguration represents an declarative configuration of the SchemaObjectReference type for use
// with apply.
type SchemaObjectReferenceApplyConfiguration struct {
	LocalObjectReferenceApplyConfiguration `json:",inline"`
}

// SchemaObjectReferenceApplyConfiguration constructs an declarative configuration of the SchemaObjectReference type for use with
// apply.
func SchemaObjectReference() *SchemaObjectReferenceApplyConfiguration {
	return &SchemaObjectReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SchemaObjectReferenceApplyConfiguration) WithName(value string) *SchemaObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}
