// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// UISchemaObjectReferenceApplyConfiguration represents an declarative configuration of the UISchemaObjectReference type for use
// with apply.
type UISchemaObjectReferenceApplyConfiguration struct {
	LocalObjectReferenceApplyConfiguration `json:",inline"`
}

// UISchemaObjectReferenceApplyConfiguration constructs an declarative configuration of the UISchemaObjectReference type for use with
// apply.
func UISchemaObjectReference() *UISchemaObjectReferenceApplyConfiguration {
	return &UISchemaObjectReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *UISchemaObjectReferenceApplyConfiguration) WithName(value string) *UISchemaObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}
