// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// VCSSourceApplyConfiguration represents an declarative configuration of the VCSSource type for use
// with apply.
type VCSSourceApplyConfiguration struct {
	TokenAuthApplyConfiguration `json:",inline"`
	Platform                    *string `json:"platform,omitempty"`
	URL                         *string `json:"url,omitempty"`
}

// VCSSourceApplyConfiguration constructs an declarative configuration of the VCSSource type for use with
// apply.
func VCSSource() *VCSSourceApplyConfiguration {
	return &VCSSourceApplyConfiguration{}
}

// WithToken sets the Token field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Token field is set to the value of the last call.
func (b *VCSSourceApplyConfiguration) WithToken(value string) *VCSSourceApplyConfiguration {
	b.Token = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *VCSSourceApplyConfiguration) WithSecretRef(value *LocalObjectReferenceApplyConfiguration) *VCSSourceApplyConfiguration {
	b.SecretRef = value
	return b
}

// WithPlatform sets the Platform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Platform field is set to the value of the last call.
func (b *VCSSourceApplyConfiguration) WithPlatform(value string) *VCSSourceApplyConfiguration {
	b.Platform = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *VCSSourceApplyConfiguration) WithURL(value string) *VCSSourceApplyConfiguration {
	b.URL = &value
	return b
}
