// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/seal-io/walrus/pkg/apis/walrusutil/v1"
	walrusutilv1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walrusutil/v1"
	scheme "github.com/seal-io/walrus/pkg/clients/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ScheduleTasksGetter has a method to return a ScheduleTaskInterface.
// A group's client should implement this interface.
type ScheduleTasksGetter interface {
	ScheduleTasks(namespace string) ScheduleTaskInterface
}

// ScheduleTaskInterface has methods to work with ScheduleTask resources.
type ScheduleTaskInterface interface {
	Create(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.CreateOptions) (*v1.ScheduleTask, error)
	Update(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.UpdateOptions) (*v1.ScheduleTask, error)
	UpdateStatus(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.UpdateOptions) (*v1.ScheduleTask, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ScheduleTask, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ScheduleTaskList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ScheduleTask, err error)
	Apply(ctx context.Context, scheduleTask *walrusutilv1.ScheduleTaskApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ScheduleTask, err error)
	ApplyStatus(ctx context.Context, scheduleTask *walrusutilv1.ScheduleTaskApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ScheduleTask, err error)
	ScheduleTaskExpansion
}

// scheduleTasks implements ScheduleTaskInterface
type scheduleTasks struct {
	client rest.Interface
	ns     string
}

// newScheduleTasks returns a ScheduleTasks
func newScheduleTasks(c *WalrusutilV1Client, namespace string) *scheduleTasks {
	return &scheduleTasks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the scheduleTask, and returns the corresponding scheduleTask object, and an error if there is any.
func (c *scheduleTasks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ScheduleTask, err error) {
	result = &v1.ScheduleTask{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scheduletasks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ScheduleTasks that match those selectors.
func (c *scheduleTasks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ScheduleTaskList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ScheduleTaskList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scheduletasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested scheduleTasks.
func (c *scheduleTasks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("scheduletasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a scheduleTask and creates it.  Returns the server's representation of the scheduleTask, and an error, if there is any.
func (c *scheduleTasks) Create(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.CreateOptions) (result *v1.ScheduleTask, err error) {
	result = &v1.ScheduleTask{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("scheduletasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduleTask).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a scheduleTask and updates it. Returns the server's representation of the scheduleTask, and an error, if there is any.
func (c *scheduleTasks) Update(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.UpdateOptions) (result *v1.ScheduleTask, err error) {
	result = &v1.ScheduleTask{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scheduletasks").
		Name(scheduleTask.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduleTask).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *scheduleTasks) UpdateStatus(ctx context.Context, scheduleTask *v1.ScheduleTask, opts metav1.UpdateOptions) (result *v1.ScheduleTask, err error) {
	result = &v1.ScheduleTask{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scheduletasks").
		Name(scheduleTask.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduleTask).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the scheduleTask and deletes it. Returns an error if one occurs.
func (c *scheduleTasks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scheduletasks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *scheduleTasks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scheduletasks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched scheduleTask.
func (c *scheduleTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ScheduleTask, err error) {
	result = &v1.ScheduleTask{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("scheduletasks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied scheduleTask.
func (c *scheduleTasks) Apply(ctx context.Context, scheduleTask *walrusutilv1.ScheduleTaskApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ScheduleTask, err error) {
	if scheduleTask == nil {
		return nil, fmt.Errorf("scheduleTask provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(scheduleTask)
	if err != nil {
		return nil, err
	}
	name := scheduleTask.Name
	if name == nil {
		return nil, fmt.Errorf("scheduleTask.Name must be provided to Apply")
	}
	result = &v1.ScheduleTask{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("scheduletasks").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *scheduleTasks) ApplyStatus(ctx context.Context, scheduleTask *walrusutilv1.ScheduleTaskApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ScheduleTask, err error) {
	if scheduleTask == nil {
		return nil, fmt.Errorf("scheduleTask provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(scheduleTask)
	if err != nil {
		return nil, err
	}

	name := scheduleTask.Name
	if name == nil {
		return nil, fmt.Errorf("scheduleTask.Name must be provided to Apply")
	}

	result = &v1.ScheduleTask{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("scheduletasks").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
