// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

// Package v1 is the v1 version of the API definitions for walrusutil group.
//
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen=package
// +k8s:protobuf-gen=package
// +domain=seal.io
// +groupName=walrusutil.seal.io
// +versionName=v1
package v1
