// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SchemaStatusApplyConfiguration represents an declarative configuration of the SchemaStatus type for use
// with apply.
type SchemaStatusApplyConfiguration struct {
	Value      []byte                           `json:"value,omitempty"`
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SchemaStatusApplyConfiguration constructs an declarative configuration of the SchemaStatus type for use with
// apply.
func SchemaStatus() *SchemaStatusApplyConfiguration {
	return &SchemaStatusApplyConfiguration{}
}

// WithValue adds the given value to the Value field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Value field.
func (b *SchemaStatusApplyConfiguration) WithValue(values ...byte) *SchemaStatusApplyConfiguration {
	for i := range values {
		b.Value = append(b.Value, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SchemaStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SchemaStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
