// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SchemaSpecApplyConfiguration represents an declarative configuration of the SchemaSpec type for use
// with apply.
type SchemaSpecApplyConfiguration struct {
	Value []byte `json:"value,omitempty"`
}

// SchemaSpecApplyConfiguration constructs an declarative configuration of the SchemaSpec type for use with
// apply.
func SchemaSpec() *SchemaSpecApplyConfiguration {
	return &SchemaSpecApplyConfiguration{}
}

// WithValue adds the given value to the Value field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Value field.
func (b *SchemaSpecApplyConfiguration) WithValue(values ...byte) *SchemaSpecApplyConfiguration {
	for i := range values {
		b.Value = append(b.Value, values[i])
	}
	return b
}
