// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	walrusutilv1 "github.com/seal-io/walrus/pkg/apis/walrusutil/v1"
	clientset "github.com/seal-io/walrus/pkg/clients/clientset"
	internalinterfaces "github.com/seal-io/walrus/pkg/clients/informers/internalinterfaces"
	v1 "github.com/seal-io/walrus/pkg/clients/listers/walrusutil/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScheduleTaskInformer provides access to a shared informer and lister for
// ScheduleTasks.
type ScheduleTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ScheduleTaskLister
}

type scheduleTaskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScheduleTaskInformer constructs a new informer for ScheduleTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScheduleTaskInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScheduleTaskInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScheduleTaskInformer constructs a new informer for ScheduleTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScheduleTaskInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WalrusutilV1().ScheduleTasks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WalrusutilV1().ScheduleTasks(namespace).Watch(context.TODO(), options)
			},
		},
		&walrusutilv1.ScheduleTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *scheduleTaskInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScheduleTaskInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scheduleTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&walrusutilv1.ScheduleTask{}, f.defaultInformer)
}

func (f *scheduleTaskInformer) Lister() v1.ScheduleTaskLister {
	return v1.NewScheduleTaskLister(f.Informer().GetIndexer())
}
